apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wva-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
imagePullSecrets:
  - name: {{ .Values.wva.imagePullSecret | default "" }}
