apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wva-controller-manager-token-manual
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-wva-controller-manager
type: kubernetes.io/service-account-token