apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}-wva-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-wva-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-wva-controller-manager
  namespace: {{ .Release.Namespace }}
