apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-wva-metrics-reader
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
