apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-wva-metrics-reader-rolebinding
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-wva-metrics-reader
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-wva-controller-manager
  namespace: {{ .Release.Namespace }}
