apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wva-prometheus-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ca.crt: |
    {{- if .Values.wva.prometheus.caCert }}
{{ .Values.wva.prometheus.caCert | indent 4 }}
    {{- else }}
    # CA certificate not provided - using system CA bundle
    {{- end }}
